name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Fix Playwright permissions
        run: chmod +x ./node_modules/.bin/playwright

      - name: Install Playwright Browsers
        run: npx playwright install chromium firefox webkit --with-deps

      - name: Run tests
        run: npx playwright test --reporter=list